version: '3.5'
services:
  server: 
    image: 2fa:latest
    ports:
      - "${SERVER_PORT}:3000"
    networks:
      local_network:
        aliases:
          - server

networks:
  local_network:
    name: local-network
