swagger: "2.0"
info:
  description: "Rest API 2FA"
  version: "1.0.0"
  title: "2FA"
host: "localhost:3000"
basePath: "/"
tags:
  - name: "User"
    description: "Operations about user"
    externalDocs:
      description: "Find out more about our store"
      url: "http://swagger.io"
schemes:
  - "https"
  - "http"
paths:
  /auth/login:
    post:
      tags:
        - "Auth"
      summary: "Login a user"
      description: "Given email and password, authenticate a user"
      operationId: "login"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/AuthLogin"
      responses:
        "400":
          description: "Auth Faild"
        "200":
          description: "Token"
          schema:
            $ref: "#/definitions/TokenDto"
  /auth/otp:
    post:
      tags:
        - "Auth"
      summary: "Check the otp"
      description: "Check the otp and return a token"
      operationId: "otpCheck"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/CheckOtp"
      responses:
        "400":
          description: "Auth Faild"
        "200":
          description: "Token"
          schema:
            $ref: "#/definitions/TokenDto"

  /user:
    post:
      tags:
        - "User"
      summary: "Create user"
      description: "Insert new user"
      operationId: "createUser"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Created user object"
          required: true
          schema:
            $ref: "#/definitions/InsertUser"
      responses:
        "201":
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
    get:
      tags:
        - "User"
      summary: "Get all users"
      description: "Get all users"
      operationId: "listUser"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: array
            items:
              $ref: "#/definitions/User"
        "400":
          description: "Invalid username/password supplied"

definitions:
  User:
    type: "object"
    properties:
      userId:
        type: "integer"
      email:
        type: "string"
      name:
        type: "string"
      surname:
        type: "string"
      otp:
        type: "boolean"
  CheckOtp:
    type: "object"
    properties:
      email:
        type: "string"
      otp:
        type: "string"
  InsertUser:
    type: "object"
    properties:
      name:
        type: "string"
      surname:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      otp:
        type: "boolean"

  TokenDto:
    type: "object"
    properties:
      token:
        type: "string"
  AuthLogin:
    type: "object"
    properties:
      email:
        type: "string"
      password:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
